global:
  resolve_timeout: 1m
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
    - send_resolved: true

